const express = require("express");
const {login ,addUser , fetchUsers , deleteUser , updateUser}  = require("../controller/login.controller");
const { auth } = require ("../middleware/auth.js");
const router = express.Router();
router.post("/login", login);
router.post("/add-user",auth,addUser);
router.get("/users",auth,fetchUsers);
router.delete("/delete/:id",auth,deleteUser);
router.put("/update/:id", auth ,updateUser);
module.exports = router;
